services:
  # Next.js Application
  needshopping-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: needshopping-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # Mount public folder for dynamic assets
      - ./public:/app/public:ro
      # Mount .env file
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - needshopping-network

networks:
  needshopping-network:
    driver: bridge